# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and pnpm lock if present
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
env NODE_ENV=production
RUN apk add --no-cache git && \
    npm install --production --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose default port (not used for stdio)
# ENTRYPOINT will be managed by MCP host
